/**
 * Export Service
 * Handles PDF, JSON, and CSV export functionality
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { Report, ThreatAssessment } from '../types/report.types';
import { format } from 'date-fns';

class ExportService {
  /**
   * Export report as PDF
   */
  async exportPDF(report: Report): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    let yPos = margin;

    // Header
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('SENTINEL', margin, yPos);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Tactical AI Intelligence Synthesizer', margin, yPos + 6);
    
    // Classification marking
    pdf.setFontSize(8);
    pdf.setTextColor(184, 150, 74); // Gold
    pdf.text('UNCLASSIFIED // FOR OFFICIAL USE ONLY', pageWidth - margin, yPos, { align: 'right' });
    pdf.setTextColor(0, 0, 0);

    yPos += 15;
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    if (!report.assessment) {
      pdf.text('No assessment available', margin, yPos);
      pdf.save(`sentinel-report-${report.id}.pdf`);
      return;
    }

    const assessment = report.assessment;

    // Report Info
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('REPORT ID:', margin, yPos);
    pdf.setFont('helvetica', 'normal');
    pdf.text(report.id, margin + 30, yPos);
    yPos += 6;

    pdf.setFont('helvetica', 'bold');
    pdf.text('TIMESTAMP:', margin, yPos);
    pdf.setFont('helvetica', 'normal');
    pdf.text(format(report.timestamp, 'yyyy-MM-dd HH:mm:ss'), margin + 30, yPos);
    yPos += 6;

    if (report.metadata.reporterId) {
      pdf.setFont('helvetica', 'bold');
      pdf.text('SOURCE:', margin, yPos);
      pdf.setFont('helvetica', 'normal');
      pdf.text(report.metadata.reporterId, margin + 30, yPos);
      yPos += 6;
    }

    yPos += 5;

    // Threat Level
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('THREAT LEVEL:', margin, yPos);
    
    // Color code threat level
    const threatColors: Record<string, [number, number, number]> = {
      CRITICAL: [139, 42, 42],
      HIGH: [218, 165, 32],
      MEDIUM: [138, 122, 58],
      LOW: [42, 106, 74]
    };
    const color = threatColors[assessment.threatLevel] || [100, 100, 100];
    pdf.setTextColor(...color);
    pdf.text(assessment.threatLevel, margin + 45, yPos);
    pdf.setTextColor(0, 0, 0);
    
    pdf.setFontSize(10);
    pdf.text(`(Confidence: ${assessment.confidence}%)`, margin + 80, yPos);
    yPos += 10;

    // Executive Summary
    pdf.setFont('helvetica', 'bold');
    pdf.text('EXECUTIVE SUMMARY', margin, yPos);
    yPos += 6;
    pdf.setFont('helvetica', 'normal');
    const summaryLines = pdf.splitTextToSize(
      assessment.executiveSummary || assessment.summary || '',
      pageWidth - 2 * margin
    );
    pdf.text(summaryLines, margin, yPos);
    yPos += summaryLines.length * 5 + 8;

    // Check if we need a new page
    if (yPos > pageHeight - 40) {
      pdf.addPage();
      yPos = margin;
    }

    // Key Findings
    pdf.setFont('helvetica', 'bold');
    pdf.text('KEY FINDINGS', margin, yPos);
    yPos += 6;
    pdf.setFont('helvetica', 'normal');
    
    assessment.keyFindings.forEach((finding, idx) => {
      if (yPos > pageHeight - 30) {
        pdf.addPage();
        yPos = margin;
      }
      const findingLines = pdf.splitTextToSize(`${idx + 1}. ${finding}`, pageWidth - 2 * margin - 5);
      pdf.text(findingLines, margin + 5, yPos);
      yPos += findingLines.length * 5 + 3;
    });

    yPos += 5;

    // Recommendations
    if (yPos > pageHeight - 40) {
      pdf.addPage();
      yPos = margin;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.text('RECOMMENDED ACTIONS', margin, yPos);
    yPos += 6;
    pdf.setFont('helvetica', 'normal');

    assessment.recommendations.forEach((rec, idx) => {
      if (yPos > pageHeight - 30) {
        pdf.addPage();
        yPos = margin;
      }
      pdf.setFont('helvetica', 'bold');
      pdf.text(`OPTION ${rec.option}:`, margin + 5, yPos);
      pdf.setFont('helvetica', 'normal');
      yPos += 5;
      const actionLines = pdf.splitTextToSize(rec.action, pageWidth - 2 * margin - 10);
      pdf.text(actionLines, margin + 10, yPos);
      yPos += actionLines.length * 5 + 5;
    });

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(100, 100, 100);
    pdf.text(
      `Generated by SENTINEL v1.0 | ${format(Date.now(), 'yyyy-MM-dd HH:mm:ss')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    // Save
    pdf.save(`sentinel-report-${report.id}.pdf`);
  }

  /**
   * Export report as JSON
   */
  exportJSON(report: Report): void {
    const dataStr = JSON.stringify(report, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sentinel-report-${report.id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export multiple reports as CSV
   */
  exportCSV(reports: Report[]): void {
    const headers = [
      'ID',
      'Timestamp',
      'Source',
      'Threat Level',
      'Confidence',
      'Summary',
      'Key Findings',
      'Recommendations'
    ];

    const rows = reports.map(report => {
      const assessment = report.assessment;
      return [
        report.id,
        format(report.timestamp, 'yyyy-MM-dd HH:mm:ss'),
        report.metadata.reporterId || 'N/A',
        assessment?.threatLevel || 'N/A',
        assessment?.confidence?.toString() || 'N/A',
        assessment?.executiveSummary || assessment?.summary || 'N/A',
        assessment?.keyFindings.join('; ') || 'N/A',
        assessment?.recommendations.map(r => r.action).join('; ') || 'N/A'
      ];
    });

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sentinel-reports-${format(Date.now(), 'yyyy-MM-dd')}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export all data as JSON backup
   */
  exportAllData(data: { reports: Report[]; config: any[] }): void {
    const dataStr = JSON.stringify(data, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sentinel-backup-${format(Date.now(), 'yyyy-MM-dd-HHmmss')}.json`;
    link.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export comparison report as PDF
   */
  async exportComparisonPDF(reports: Report[], analysis: any): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 15;
    let yPos = margin;

    // Header
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('MULTI-REPORT COMPARISON', margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Comparing ${reports.length} reports`, margin, yPos);
    yPos += 6;
    pdf.text(`Generated: ${format(Date.now(), 'yyyy-MM-dd HH:mm:ss')}`, margin, yPos);
    yPos += 10;

    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    // Common threats
    if (analysis.commonThreats && analysis.commonThreats.length > 0) {
      pdf.setFont('helvetica', 'bold');
      pdf.text('COMMON THREATS', margin, yPos);
      yPos += 6;
      pdf.setFont('helvetica', 'normal');

      analysis.commonThreats.forEach((threat: string, idx: number) => {
        const lines = pdf.splitTextToSize(`• ${threat}`, pageWidth - 2 * margin);
        pdf.text(lines, margin + 5, yPos);
        yPos += lines.length * 5 + 2;
      });

      yPos += 5;
    }

    // Save
    pdf.save(`sentinel-comparison-${format(Date.now(), 'yyyy-MM-dd')}.pdf`);
  }
}

export default new ExportService();
